local wt = WidgetTools.toolboxes.initialization[C_AddOns.GetAddOnMetadata(..., "Version")] ---@type toolbox

if not wt then return end

--[ Changelog ]

wt.changelog = {
    {
        "#V_Version 3.0_# #H_(23/4/2026)_#",
        "#F_Hotfix (Version 3.0.1):_#",
        "Des sécurités ont été ajoutées à plusieurs endroits pour empêcher que des chemins de fichiers de ressources manquants ou invalides (polices ou textures) provoquent des erreurs critiques.",
        "#N_Nouveau:_#",
        "Ajout de la compatibilité avec Midnight 12.0.5.",
        "Les menus contextuels (clic droit) ajoutés précédemment pour les paramètres ont été améliorés avec des fonctions de copier/coller permettant de transférer facilement des valeurs entre types de paramètres similaires.",
        "Ajout d’un nouveau modèle avancé de paramètres pour la gestion des options de Polices (davantage d’options de personnalisation arriveront dans de futures mises à jour).",
        "#C_Modifications:_#",
        "L’apparence des curseurs numériques de paramètres a été mise à jour pour correspondre aux nouveaux curseurs Blizzard, tout en conservant toutes les fonctionnalités améliorées habituelles pour les addons construits avec Widget Tools Toolboxes.",
        "La structure de chargement de la Toolbox a été remaniée ; les anciennes versions ne sont plus prises en charge.",
        "De nombreuses fonctions utilitaires de base ont été transférées vers Widget Tools (et ne sont plus spécifiques à la Toolbox), accessibles globalement via la collection WidgetTools.utilities.",
        "Les données spécifiques à la Toolbox ne seront plus injectées dans les tables de frames, mais stockées dans des tables dédiées à la Toolbox (y compris les données d’agencement de tooltips ou de conteneurs).",
        "Le système backend de gestion des événements pour les gestionnaires OnEvent globaux de Blizzard (et les événements personnalisés) a été mis à jour, avec de nouveaux utilitaires accessibles globalement via WidgetTools.utilities.",
        "Les Frames, Boutons et autres widgets personnalisables doivent désormais être créés via de nouveaux constructeurs ; les indicateurs de personnalisation ont été retirés de leurs versions de base.",
        "La plupart des annotations destinées uniquement au développement ont été déplacées hors des fichiers installés de l’addon afin de réduire considérablement la taille d’installation.",
        "La logique de construction de la page de gestion des données (désormais appelée page de profils) a été séparée en un widget profilemanager et une mutation d’interface par-dessus, permettant davantage de flexibilité et de personnalisation.",
        "Plusieurs autres améliorations et changements internes.",
        "#F_Correctifs:_#",
        "De nombreux autres correctifs mineurs.",
        "#H_Merci à tous pour votre aide, vos suggestions et vos rapports de bugs !_# Si vous rencontrez un problème, n’hésitez pas à le signaler ! Essayez d’indiquer quand et comment il se produit, ainsi que les autres addons utilisés (si pertinent), afin de me donner les meilleures chances de le reproduire et de le corriger. Fournissez si possible les messages d’erreur Lua et les journaux de taint (si vous savez comment les obtenir).",
    }
}

--[ Strings ]

--NOTE: #FLAGS will be replaced by text or number values via code; \n represents the newline character

---French
---@class toolboxStrings_frFR
wt.strings = {
	date = "#DAY/#MONTH/#YEAR",

	override = "Écraser",
	example = "Exemple",

	chat_welcome_thanks = "Merci d'utiliser #ADDON !",
	chat_welcome_hint = "Tapez #KEYWORD pour voir la liste des commandes du chat.",
	chat_welcome_keywords = "#KEYWORD ou #KEYWORD_ALTERNATE",
	chat_help_list = "Liste des commandes du chat de #ADDON :",

	popupInput_title = "Spécifiez le texte",
	popupInput_tooltip = "Appuyez sur " .. KEY_ENTER .. " pour valider le texte ou sur " .. KEY_ESCAPE .. " pour annuler.",

	reload_title = "Modifications en attente",
	reload_description = "Rechargez l'interface pour appliquer les modifications en attente.",
	reload_accept_label = "Recharger maintenant",
	reload_accept_tooltip = "Vous pouvez choisir de recharger l'interface maintenant pour appliquer les modifications en attente.",
	reload_cancel_label = "Plus tard",
	reload_cancel_tooltip = "Rechargez l'interface plus tard avec la commande /reload ou en vous déconnectant.",

	multiSelector_locked = "Verrouillé",
	multiSelector_minLimit = "Au moins #MIN options doivent être sélectionnées.",
	multiSelector_maxLimit = "Seulement #MAX options peuvent être sélectionnées à la fois.",

	dropdown_selected = "Ceci est l'option actuellement sélectionnée.",
	dropdown_none = "Aucune option n'a été sélectionnée.",
	dropdown_open = "Cliquez pour voir la liste des options.",
	dropdown_previous_label = "Option précédente",
	dropdown_previous_tooltip = "Sélectionner l'option précédente.",
	dropdown_next_label = "Option suivante",
	dropdown_next_tooltip = "Sélectionner l'option suivante.",
	dropdown_clear = "Effacer la sélection",

	copyBox_tooltip = "Copiez le texte en appuyant sur :\n" .. CTRL_KEY_TEXT .." + C (Windows)\n" .. COMMAND .. " + C (Mac)",

	slider_value_label = "Spécifiez la valeur",
	slider_value_tooltip = "Entrez une valeur dans la plage autorisée.",
	slider_decrease_label = "Diminuer",
	slider_decrease_tooltip = {
		"Soustraire #VALUE de la valeur.",
		"Maintenez ALT pour soustraire #VALUE à la place.",
	},
	slider_increase_label = "Augmenter",
	slider_increase_tooltip = {
		"Ajouter #VALUE à la valeur.",
		"Maintenez ALT pour ajouter #VALUE à la place.",
	},

	color_picker_label = "Choisir une couleur",
	color_picker_tooltip = "Ouvrez le sélecteur de couleur pour personnaliser la couleur#ALPHA.",
	color_picker_alpha = " et modifier l'opacité",
	color_hex_label = "Ajouter via code couleur HEX",
	color_hex_tooltip = "Vous pouvez changer la couleur via un code HEX au lieu d'utiliser le sélecteur de couleur.",

	settings_save = "Les modifications seront appliquées à la fermeture.",
	settings_cancel_label = "Annuler les modifications",
	settings_cancel_tooltip = "Annuler toutes les modifications apportées à cette page et charger les valeurs enregistrées.",
	settings_defaults_label = "Restaurer les valeurs par défaut",
	settings_defaults_tooltip = "Restaurer tous les paramètres de cette page (ou de la catégorie entière) aux valeurs par défaut.",
	settings_warning = "Êtes-vous sûr de vouloir réinitialiser les paramètres de la page #PAGE ou tous les paramètres de la catégorie #CATEGORY aux valeurs par défaut ?",
	settings_warningSingle = "Êtes-vous sûr de vouloir réinitialiser les paramètres de la page #PAGE aux valeurs par défaut ?",

	value_copy = "Copier la valeur",
	value_paste = "Coller la valeur",
	value_revert = "Annuler les modifications",
	value_restore = "Restaurer la valeur par défaut",
	value_note = "Faites un clic droit pour copier ou annuler.",

	points_left = "Gauche",
	points_right = "Droite",
	points_center = "Centre",
	points_top_left = "En haut à gauche",
	points_top_right = "En haut à droite",
	points_top_center = "En haut au centre",
	points_bottom_left = "En bas à gauche",
	points_bottom_right = "En bas à droite",
	points_bottom_center = "En bas au centre",

	strata_lowest = "Arrière-plan bas",
	strata_lower = "Arrière-plan moyen",
	strata_low = "Arrière-plan haut",
	strata_lowMid = "Bas milieu",
	strata_highMid = "Haut milieu",
	strata_high = "Premier plan bas",
	strata_higher = "Premier plan moyen",
	strata_highest = "Premier plan haut",

	about_title = "À propos",
	about_description = "Merci d'utiliser #ADDON ! Copiez les liens pour savoir comment donner votre avis, obtenir de l'aide et soutenir le développement.",
	about_version = "Version",
	about_date = "Date",
	about_author = "Auteur",
	about_license = "Licence",
	about_curseForge = "Page CurseForge",
	about_wago = "Page Wago",
	about_repository = "Dépôt GitHub",
	about_issues = "Problèmes & Retours",
	about_changelog_label = "Notes de mise à jour",
	about_changelog_tooltip = "Notes de tous les changements, mises à jour et corrections introduits dans la dernière version : #VERSION.",
	about_fullChangelog_label = "Historique de #ADDON",
	about_fullChangelog_tooltip = "La liste complète des notes de mise à jour de toutes les versions de l'addon.",
	about_fullChangelog_open_label = "Historique",
	about_fullChangelog_open_tooltip = "Lire la liste complète des notes de mise à jour de toutes les versions de l'addon.",

	sponsors_title = "Sponsors",
	sponsors_description = "Votre soutien continu est très apprécié ! Merci !",

	profilesPage_title = "Profils & Sauvegardes",
	profilesPage_description = "Configurez davantage #ADDON en gérant les profils et sauvegardes via les options d'import/export.",

	profiles_title = "Profils",
	profiles_description = "Créez, modifiez et appliquez des profils d'options uniques pour chacun de vos personnages.",
	profiles_select_label = "Sélectionner un profil",
	profiles_select_tooltip = "Choisissez le profil de stockage des options à utiliser pour votre personnage actuel.\n\nLes données du profil actif seront automatiquement écrasées lorsque les paramètres seront modifiés et enregistrés !",
	profiles_select_profile = "Profil",
	profiles_select_main = "Principal",
	profiles_new_label = "Nouveau profil",
	profiles_new_tooltip = "Créer un nouveau profil par défaut.",
	profiles_duplicate_label = "Dupliquer",
	profiles_duplicate_tooltip = "Créer un nouveau profil en copiant les données du profil actif.",
	profiles_rename_label = "Renommer",
	profiles_rename_tooltip = "Renommer le profil actif.",
	profiles_rename_description = "Renommer #PROFILE en :",
	profiles_delete_tooltip = "Supprimer le profil actif.",
	profiles_delete_warning = "Êtes-vous sûr de vouloir supprimer le profil de paramètres #PROFILE #ADDON actif et de supprimer définitivement toutes les données qui y sont stockées ?",
	profiles_reset_warning = "Êtes-vous sûr de vouloir écraser le profil de paramètres #PROFILE #ADDON actif avec les valeurs par défaut ?",

	backup_title = "Sauvegarde",
	backup_description = "Importez ou exportez les données du profil actif pour sauvegarder, partager ou transférer les paramètres, ou modifier des valeurs manuellement.",
	backup_box_label = "Importer ou exporter le profil actuel",
	backup_box_tooltip = {
		"La chaîne de sauvegarde de ce champ contient les données du profil actif de l'addon.",
		"Copiez le texte pour sauvegarder, partager ou charger des données pour un autre compte.",
		"Pour charger des données à partir d'une chaîne, remplacez le texte de ce champ, puis appuyez sur " .. KEY_ENTER .. " ou cliquez sur le bouton #LOAD.",
		"Remarque : Si vous utilisez des fichiers de police ou de texture personnalisés, ces fichiers ne seront pas transférés avec cette chaîne. Ils devront être enregistrés séparément et placés dans le dossier de l'addon pour être utilisables.",
		"Ne chargez que des chaînes que vous avez vérifiées vous-même ou qui proviennent d'une source de confiance !",
	},
	backup_allProfiles_label = "Importer ou exporter tous les profils",
	backup_allProfiles_tooltipLine = "La chaîne de sauvegarde de ce champ contient la liste de tous les profils de l'addon et les données stockées dans chacun, ainsi que le nom du profil actif.",
	backup_allProfiles_open_label = "Tous les profils",
	backup_allProfiles_open_tooltip = "Accédez à la liste complète des profils et sauvegardez ou modifiez les données stockées dans chacun.",
	backup_compact_label = "Compact",
	backup_compact_tooltip = "Basculer entre une vue compacte et une vue plus lisible/modifiable.",
	backup_load_label = "Charger",
	backup_load_tooltip = "Vérifiez la chaîne actuelle et essayez de charger les données à partir de celle-ci.",
	backup_reset_tooltip = "Annuler toutes les modifications apportées à la chaîne et la réinitialiser pour contenir les données actuellement enregistrées.",
	backup_import = "Charger la chaîne",
	backup_warning = "Êtes-vous sûr de vouloir tenter de charger la chaîne actuellement saisie ?\n\nToutes les modifications non enregistrées seront annulées.\n\nSi vous l'avez copiée d'une source en ligne ou si quelqu'un vous l'a envoyée, ne la chargez qu'après avoir vérifié le code et être sûr de ce que vous faites.\n\nSi vous ne faites pas confiance à la source, annulez pour éviter toute action indésirable.",
	backup_error = "La chaîne de sauvegarde fournie n'a pas pu être validée et aucune donnée n'a été chargée. Il se peut qu'il manque des caractères ou que des erreurs aient été introduites lors de l'édition.",

	position_title = "Position",
	position_description_static = "Ajustez précisément la position de #FRAME à l'écran via les options fournies ici.",
	position_description_movable = "Faites glisser #FRAME en maintenant SHIFT pour le positionner n'importe où à l'écran, puis ajustez-le ici.",
	position_relativePoint_label = "Point de référence à l'écran",
	position_relativePoint_tooltip = "Attachez le point d'ancrage choisi de #FRAME au point de référence sélectionné ici.",
	-- position_relativeTo_label = "Lier à une frame",
	-- position_relativeTo_tooltip = "Tapez le nom d'un autre élément d'interface pour lier la position de #FRAME.\n\nTrouvez les noms des frames en activant l'interface de debug via la commande /framestack.",
	position_anchor_label = "Point d'ancrage",
	position_anchor_tooltip = "Sélectionnez le point de #FRAME à utiliser comme ancrage lors de sa liaison au point de référence à l'écran choisi.",
	position_keepInPlace_label = "Garder en place",
	position_keepInPlace_tooltip = "Ne déplacez pas #FRAME lors du changement de #ANCHOR, mettez à jour les valeurs de décalage à la place.",
	position_offsetX_label = "Décalage horizontal",
	position_offsetX_tooltip = "Définissez la quantité de décalage horizontal (axe X) de #FRAME à partir de l'#ANCHOR sélectionné.",
	position_offsetY_label = "Décalage vertical",
	position_offsetY_tooltip = "Définissez la quantité de décalage vertical (axe Y) de #FRAME à partir de l'#ANCHOR sélectionné.",
	position_keepInBounds_label = "Garder dans les limites de l'écran",
	position_keepInBounds_tooltip = "Assurez-vous que #FRAME ne puisse pas être déplacé hors de l'écran.",

	presets_apply_label = "Appliquer un préréglage",
	presets_apply_tooltip = "Changez la position de #FRAME en choisissant et en appliquant un de ces préréglages.",
	presets_apply_list = { "Sous la Minicarte", },
	presets_apply_select = "Sélectionnez un préréglage…",
	presets_save_label = "Mettre à jour le préréglage #CUSTOM",
	presets_save_tooltip = "Enregistrez la position et la visibilité actuelles de #FRAME dans le préréglage #CUSTOM.",
	presets_save_warning = "Êtes-vous sûr de vouloir écraser le préréglage #CUSTOM avec les valeurs actuelles ?",
	presets_reset_label = "Réinitialiser le préréglage #CUSTOM",
	presets_reset_tooltip = "Écrasez les données du préréglage #CUSTOM avec les valeurs par défaut, puis appliquez-le.",
	presets_reset_warning = "Êtes-vous sûr de vouloir écraser le préréglage #CUSTOM avec les valeurs par défaut ?",

	layer_strata_label = "Calque d'écran",
	layer_strata_tooltip = "Montez ou descendez #FRAME pour qu'il soit devant ou derrière d'autres éléments de l'interface.",
	layer_keepOnTop_label = "Afficher lors d'une interaction avec la souris",
	layer_keepOnTop_tooltip = "Permettre à #FRAME d'être déplacé au-dessus d'autres frames dans la même #STRATA lors d'une interaction.",
	layer_level_label = "Niveau de frame",
	layer_level_tooltip = "La position exacte de #FRAME au-dessus ou en dessous d'autres frames dans la même pile #STRATA.",

	font_title = "Texte",
	font_path_label = "Police",
	font_path_tooltip = "Sélectionnez la police.",
	font_path_default_label = "Police par défaut localisée",
	font_path_default_tooltip = "Ceci est une police par défaut localisée utilisée par Blizzard.",
	font_path_base = "Ceci est une police du jeu de base.",
	font_path_custom = "Ceci est une police personnalisée.",
	font_path_otf = "Licence de police OpenType.",
	font_path_file = "Chemin du fichier : #PATH",
	font_path_replace = "L’option Personnalisée offre une personnalisation complète en vous permettant d’utiliser n’importe quelle police en remplaçant le fichier de police #FILE_CUSTOM par n’importe quel autre fichier TrueType trouvé dans\n#FONTS_DIRECTORY\ntout en conservant son nom de fichier #FILE_CUSTOM.",
	font_path_reminder = "Vous devrez peut-être redémarrer complètement le client du jeu après avoir remplacé le fichier de police pour appliquer le changement.",
	font_size_label = "Taille",
	font_size_tooltip = "Définissez la taille de la police.",
	font_alignment_label = "Alignement",
	font_alignment_tooltip = "Sélectionnez l’alignement horizontal du texte.",
	font_color_label = "Couleur #COLOR_TYPE",
	font_color_tooltip = "Définissez la couleur du texte #COLOR_TYPE.",
}