local wt = WidgetTools.toolboxes.initialization[C_AddOns.GetAddOnMetadata(..., "Version")] ---@type toolbox

if not wt then return end

--[ Changelog ]

wt.changelog = {
    {
        "#V_Version 3.0_# #H_(23/4/2026)_#",
        "#F_Hotfix (Versione 3.0.1):_#",
        "Sono state aggiunte protezioni in vari punti per impedire che percorsi mancanti o non validi di file di risorse (font o texture) causino errori critici.",
        "#N_Nuovo:_#",
        "Aggiunto il supporto per Midnight 12.0.5.",
        "I menu di clic destro per le impostazioni aggiunti in precedenza sono stati ulteriormente migliorati con funzionalità di copia e incolla per spostare facilmente i valori tra tipi di impostazioni simili.",
        "Aggiunto un nuovo modello avanzato di impostazioni per la gestione delle opzioni dei Font (ulteriori opzioni di personalizzazione arriveranno in aggiornamenti futuri).",
        "#C_Modifiche:_#",
        "L’aspetto degli slider numerici delle impostazioni è stato aggiornato per allinearsi ai nuovi slider Blizzard, mantenendo tutte le funzionalità avanzate tipiche degli addon costruiti con Widget Tools Toolboxes.",
        "La struttura di caricamento della Toolbox è stata revisionata; le versioni precedenti non sono più supportate.",
        "Molte funzioni di utilità di base sono state trasferite a Widget Tools (e non sono più specifiche della Toolbox), accessibili globalmente tramite la collezione WidgetTools.utilities.",
        "I dati specifici della Toolbox non verranno più iniettati nelle tabelle dei frame, ma conservati in tabelle dedicate alla Toolbox (inclusi i dati di disposizione di tooltip o contenitori).",
        "Il sistema backend di gestione degli eventi per gli handler OnEvent globali di Blizzard (e gli eventi personalizzati) è stato aggiornato, con nuove utilità accessibili globalmente tramite WidgetTools.utilities.",
        "I Frame, Pulsanti e altri widget personalizzabili devono ora essere creati tramite nuovi costruttori; i flag di personalizzazione sono stati rimossi dalle loro versioni base.",
        "La maggior parte delle annotazioni destinate esclusivamente allo sviluppo è stata spostata fuori dai file installati dell’addon per ridurre notevolmente la dimensione dell’installazione.",
        "La logica di costruzione della pagina di gestione dei dati (ora chiamata pagina dei profili) è stata separata in un widget profilemanager e una mutazione GUI sovrastante, per consentire maggiore flessibilità e personalizzazione.",
        "Altre varie modifiche e miglioramenti interni.",
        "#F_Correzioni:_#",
        "Numerose altre piccole correzioni.",
        "#H_Grazie a tutti per l’aiuto, i suggerimenti e le segnalazioni di bug !_# Se riscontrate problemi, non esitate a segnalarli! Cercate di includere quando e come si verificano, e quali altri addon utilizzate (se rilevante), per darmi la migliore possibilità di riprodurli e risolverli. Fornite eventuali messaggi di errore Lua e log di taint se sapete come ottenerli.",
    }
}

--[ Strings ]

--NOTE: #FLAGS will be replaced by text or number values via code; \n represents the newline character

---Italian
---@class toolboxStrings_itIT
wt.strings = {
	date = "#DAY/#MONTH/#YEAR",

	override = "Sovrascrivi",
	example = "Esempio",

	chat_welcome_thanks = "Grazie per aver utilizzato #ADDON!",
	chat_welcome_hint = "Digita #KEYWORD per vedere la lista dei comandi della chat.",
	chat_welcome_keywords = "#KEYWORD o #KEYWORD_ALTERNATE",
	chat_help_list = "Lista dei comandi della chat di #ADDON:",

	popupInput_title = "Specifica il testo",
	popupInput_tooltip = "Premi " .. KEY_ENTER .. " per accettare il testo specificato o " .. KEY_ESCAPE .. " per annullare.",

	reload_title = "Modifiche in sospeso",
	reload_description = "Ricarica l'interfaccia per applicare le modifiche in sospeso.",
	reload_accept_label = "Ricarica ora",
	reload_accept_tooltip = "Puoi scegliere di ricaricare l'interfaccia ora per applicare le modifiche in sospeso.",
	reload_cancel_label = "Più tardi",
	reload_cancel_tooltip = "Ricarica l'interfaccia più tardi con il comando /reload o disconnettendoti.",

	multiSelector_locked = "Bloccato",
	multiSelector_minLimit = "Devono essere selezionate almeno #MIN opzioni.",
	multiSelector_maxLimit = "Possono essere selezionate solo #MAX opzioni alla volta.",

	dropdown_selected = "Questa è l'opzione attualmente selezionata.",
	dropdown_none = "Nessuna opzione selezionata.",
	dropdown_open = "Clicca per vedere la lista delle opzioni.",
	dropdown_previous_label = "Opzione precedente",
	dropdown_previous_tooltip = "Seleziona l'opzione precedente.",
	dropdown_next_label = "Opzione successiva",
	dropdown_next_tooltip = "Seleziona l'opzione successiva.",
	dropdown_clear = "Cancella selezione",

	copyBox_tooltip = "Copia il testo premendo:\n" .. CTRL_KEY_TEXT .." + C (Windows)\n" .. COMMAND .. " + C (Mac)",

	slider_value_label = "Specifica il valore",
	slider_value_tooltip = "Inserisci un valore compreso nell'intervallo.",
	slider_decrease_label = "Diminuisci",
	slider_decrease_tooltip = {
		"Sottrai #VALUE dal valore.",
		"Tieni premuto ALT per sottrarre #VALUE invece.",
	},
	slider_increase_label = "Aumenta",
	slider_increase_tooltip = {
		"Aggiungi #VALUE al valore.",
		"Tieni premuto ALT per aggiungere #VALUE invece.",
	},

	color_picker_label = "Scegli un colore",
	color_picker_tooltip = "Apri il selettore colori per personalizzare il colore#ALPHA.",
	color_picker_alpha = " e modificarne l'opacità",
	color_hex_label = "Aggiungi tramite codice colore HEX",
	color_hex_tooltip = "Puoi cambiare il colore tramite codice HEX invece di usare il selettore colori.",

	settings_save = "Le modifiche saranno applicate alla chiusura.",
	settings_cancel_label = "Annulla modifiche",
	settings_cancel_tooltip = "Annulla tutte le modifiche fatte in questa pagina e carica i valori salvati.",
	settings_defaults_label = "Ripristina predefiniti",
	settings_defaults_tooltip = "Ripristina tutte le impostazioni di questa pagina (o dell'intera categoria) ai valori predefiniti.",
	settings_warning = "Sei sicuro di voler ripristinare le impostazioni della pagina #PAGE o tutte le impostazioni della categoria #CATEGORY ai valori predefiniti?",
	settings_warningSingle = "Sei sicuro di voler ripristinare le impostazioni della pagina #PAGE ai valori predefiniti?",

	value_copy = "Copia valore",
	value_paste = "Incolla valore",
	value_revert = "Annulla modifiche",
	value_restore = "Ripristina predefinito",
	value_note = "Clic destro per copiare o annullare.",

	points_left = "Sinistra",
	points_right = "Destra",
	points_center = "Centro",
	points_top_left = "In alto a sinistra",
	points_top_right = "In alto a destra",
	points_top_center = "In alto al centro",
	points_bottom_left = "In basso a sinistra",
	points_bottom_right = "In basso a destra",
	points_bottom_center = "In basso al centro",

	strata_lowest = "Sfondo Basso",
	strata_lower = "Sfondo Medio",
	strata_low = "Sfondo Alto",
	strata_lowMid = "Medio Basso",
	strata_highMid = "Medio Alto",
	strata_high = "Primo Piano Basso",
	strata_higher = "Primo Piano Medio",
	strata_highest = "Primo Piano Alto",

	about_title = "Informazioni",
	about_description = "Grazie per aver utilizzato #ADDON! Copia i link per sapere come inviare feedback, ottenere aiuto e supportare lo sviluppo.",
	about_version = "Versione",
	about_date = "Data",
	about_author = "Autore",
	about_license = "Licenza",
	about_curseForge = "Pagina CurseForge",
	about_wago = "Pagina Wago",
	about_repository = "Repository GitHub",
	about_issues = "Problemi & Feedback",
	about_changelog_label = "Note di aggiornamento",
	about_changelog_tooltip = "Note di tutti i cambiamenti, aggiornamenti e correzioni introdotti con l'ultima versione: #VERSION.",
	about_fullChangelog_label = "Changelog di #ADDON",
	about_fullChangelog_tooltip = "L'elenco completo delle note di aggiornamento di tutte le versioni dell'addon.",
	about_fullChangelog_open_label = "Changelog",
	about_fullChangelog_open_tooltip = "Leggi l'elenco completo delle note di aggiornamento di tutte le versioni dell'addon.",

	sponsors_title = "Sponsor",
	sponsors_description = "Il tuo continuo supporto è molto apprezzato! Grazie!",

	profilesPage_title = "Profili & Backup",
	profilesPage_description = "Configura ulteriormente #ADDON gestendo profili e backup tramite importazione ed esportazione.",

	profiles_title = "Profili",
	profiles_description = "Crea, modifica e applica profili di opzioni unici per ciascuno dei tuoi personaggi.",
	profiles_select_label = "Seleziona un Profilo",
	profiles_select_tooltip = "Scegli il profilo di archiviazione delle opzioni da usare per il tuo personaggio attuale.\n\nI dati nel profilo attivo verranno sovrascritti automaticamente quando le impostazioni vengono modificate e salvate!",
	profiles_select_profile = "Profilo",
	profiles_select_main = "Principale",
	profiles_new_label = "Nuovo Profilo",
	profiles_new_tooltip = "Crea un nuovo profilo predefinito.",
	profiles_duplicate_label = "Duplica",
	profiles_duplicate_tooltip = "Crea un nuovo profilo copiando i dati dal profilo attivo.",
	profiles_rename_label = "Rinomina",
	profiles_rename_tooltip = "Rinomina il profilo attivo.",
	profiles_rename_description = "Rinomina #PROFILE in:",
	profiles_delete_tooltip = "Elimina il profilo attivo.",
	profiles_delete_warning = "Sei sicuro di voler rimuovere il profilo #PROFILE #ADDON attivo e cancellare definitivamente tutti i dati in esso contenuti?",
	profiles_reset_warning = "Sei sicuro di voler sovrascrivere il profilo #PROFILE #ADDON attivo con i valori predefiniti?",

	backup_title = "Backup",
	backup_description = "Importa o esporta i dati del profilo attivo per salvare, condividere o spostare le impostazioni, o modificare manualmente i valori.",
	backup_box_label = "Importa o Esporta Profilo Attuale",
	backup_box_tooltip = {
		"La stringa di backup in questo campo contiene i dati del profilo attivo dell'addon.",
		"Copia il testo per salvare, condividere o caricare dati per un altro account.",
		"Per caricare dati da una stringa, sostituisci il testo in questo campo e premi " .. KEY_ENTER .. " o clicca sul pulsante #LOAD.",
		"Nota: Se usi file di font o texture personalizzati, questi file non verranno trasferiti con questa stringa. Dovranno essere salvati separatamente e inseriti nella cartella dell'addon per essere utilizzabili.",
		"Carica solo stringhe che hai verificato personalmente o che provengono da una fonte attendibile!",
	},
	backup_allProfiles_label = "Importa o Esporta Tutti i Profili",
	backup_allProfiles_tooltipLine = "La stringa di backup in questo campo contiene l'elenco di tutti i profili dell'addon e i dati memorizzati in ciascuno, oltre al nome del profilo attivo.",
	backup_allProfiles_open_label = "Tutti i Profili",
	backup_allProfiles_open_tooltip = "Accedi all'elenco completo dei profili e fai backup o modifica i dati memorizzati in ciascuno.",
	backup_compact_label = "Compatto",
	backup_compact_tooltip = "Alterna tra una visualizzazione compatta e una più leggibile/modificabile.",
	backup_load_label = "Carica",
	backup_load_tooltip = "Controlla la stringa attuale e prova a caricare i dati da essa.",
	backup_reset_tooltip = "Annulla tutte le modifiche apportate alla stringa e ripristinala ai dati attualmente salvati.",
	backup_import = "Carica la stringa",
	backup_warning = "Sei sicuro di voler tentare di caricare la stringa inserita?\n\nTutte le modifiche non salvate verranno annullate.\n\nSe l'hai copiata da una fonte online o qualcuno te l'ha inviata, caricala solo dopo aver controllato il codice e solo se sai cosa stai facendo.\n\nSe non ti fidi della fonte, annulla per evitare azioni indesiderate.",
	backup_error = "La stringa di backup fornita non può essere validata e nessun dato è stato caricato. Potrebbero mancare caratteri o essere stati introdotti errori durante la modifica.",

	position_title = "Posizione",
	position_description_static = "Regola la posizione di #FRAME sullo schermo tramite le opzioni qui fornite.",
	position_description_movable = "Trascina #FRAME tenendo premuto SHIFT per posizionarlo ovunque sullo schermo, quindi regolane con precisione la posizione qui.",
	position_relativePoint_label = "Punto di riferimento sullo schermo",
	position_relativePoint_tooltip = "Collega il punto di ancoraggio scelto di #FRAME al punto di riferimento selezionato qui.",
	-- position_relativeTo_label = "Collega a Frame",
	-- position_relativeTo_tooltip = "Digita il nome di un altro elemento UI, un frame a cui collegare la posizione di #FRAME.\n\nScopri i nomi dei frame attivando la UI di debug tramite il comando /framestack.",
	position_anchor_label = "Punto di Ancoraggio",
	position_anchor_tooltip = "Seleziona il punto di #FRAME da usare come ancoraggio quando viene collegato al punto di riferimento sullo schermo.",
	position_keepInPlace_label = "Mantieni in posizione",
	position_keepInPlace_tooltip = "Non spostare #FRAME quando cambi #ANCHOR, aggiorna invece i valori di offset.",
	position_offsetX_label = "Offset Orizzontale",
	position_offsetX_tooltip = "Imposta la quantità di offset orizzontale (asse X) di #FRAME dal #ANCHOR selezionato.",
	position_offsetY_label = "Offset Verticale",
	position_offsetY_tooltip = "Imposta la quantità di offset verticale (asse Y) di #FRAME dal #ANCHOR selezionato.",
	position_keepInBounds_label = "Mantieni nei limiti dello schermo",
	position_keepInBounds_tooltip = "Assicurati che #FRAME non possa essere spostato fuori dai limiti dello schermo.",

	presets_apply_label = "Applica una preimpostazione",
	presets_apply_tooltip = "Cambia la posizione di #FRAME scegliendo e applicando una di queste preimpostazioni.",
	presets_apply_list = { "Sotto la Minimap", },
	presets_apply_select = "Seleziona una preimpostazione…",
	presets_save_label = "Aggiorna preimpostazione #CUSTOM",
	presets_save_tooltip = "Salva la posizione e la visibilità attuali di #FRAME nella preimpostazione #CUSTOM.",
	presets_save_warning = "Sei sicuro di voler sovrascrivere la preimpostazione #CUSTOM con i valori attuali?",
	presets_reset_label = "Ripristina preimpostazione #CUSTOM",
	presets_reset_tooltip = "Sovrascrivi i dati salvati della preimpostazione #CUSTOM con i valori predefiniti e applicala.",
	presets_reset_warning = "Sei sicuro di voler sovrascrivere la preimpostazione #CUSTOM con i valori predefiniti?",

	layer_strata_label = "Livello Schermo",
	layer_strata_tooltip = "Alza o abbassa #FRAME per essere davanti o dietro altri elementi UI.",
	layer_keepOnTop_label = "Porta in primo piano all'interazione con il mouse",
	layer_keepOnTop_tooltip = "Consenti a #FRAME di essere portato sopra gli altri frame nello stesso #STRATA quando interagisci con esso.",
	layer_level_label = "Livello del Frame",
	layer_level_tooltip = "La posizione esatta di #FRAME sopra o sotto altri frame nello stesso stack #STRATA.",

	font_title = "Testo",
	font_path_label = "Carattere",
	font_path_tooltip = "Seleziona il carattere.",
	font_path_default_label = "Predefinito localizzato",
	font_path_default_tooltip = "Questo è un carattere predefinito localizzato usato da Blizzard.",
	font_path_base = "Questo è un carattere del gioco base.",
	font_path_custom = "Questo è un carattere personalizzato.",
	font_path_otf = "Licenza del font OpenType.",
	font_path_file = "Percorso del file: #PATH",
	font_path_replace = "L’opzione Personalizzato offre una completa personalizzazione permettendoti di usare qualsiasi carattere sostituendo il file #FILE_CUSTOM con un qualsiasi altro file TrueType trovato in\n#FONTS_DIRECTORY\nmantenendo il nome originale del file #FILE_CUSTOM.",
	font_path_reminder = "Potrebbe essere necessario riavviare completamente il client di gioco dopo aver sostituito il file del carattere per applicare la modifica.",
	font_size_label = "Dimensione",
	font_size_tooltip = "Imposta la dimensione del carattere.",
	font_alignment_label = "Allineamento",
	font_alignment_tooltip = "Seleziona l’allineamento orizzontale del testo.",
	font_color_label = "Colore #COLOR_TYPE",
	font_color_tooltip = "Imposta il colore del testo #COLOR_TYPE.",
}