local wt = WidgetTools.toolboxes.initialization[C_AddOns.GetAddOnMetadata(..., "Version")] ---@type toolbox

if not wt then return end

--[ Changelog ]

wt.changelog = {
    {
        "#V_Version 3.0_# #H_(23/4/2026)_#",
        "#F_핫픽스 (버전 3.0.1):_#",
        "여러 위치에 보호 장치를 추가하여 누락되었거나 잘못된 에셋 파일 경로(폰트 또는 텍스처)로 인해 치명적인 오류가 발생하지 않도록 했습니다.",
        "#N_새로운 기능:_#",
        "Midnight 12.0.5 지원이 추가되었습니다.",
        "이전에 추가된 설정 우클릭 메뉴가 더욱 향상되어, 유사한 유형의 설정 간에 값을 쉽게 이동할 수 있도록 복사 및 붙여넣기 기능이 추가되었습니다.",
        "폰트 옵션을 관리하기 위한 새로운 고급 설정 템플릿이 추가되었습니다 (향후 업데이트에서 더 많은 폰트 사용자 지정 옵션이 제공될 예정입니다).",
        "#C_변경 사항:_#",
        "설정 숫자 슬라이더의 외형이 새로운 블리자드 슬라이더와 일치하도록 업데이트되었으며, Widget Tools Toolboxes로 제작된 애드온의 모든 향상된 기능은 그대로 유지됩니다.",
        "Toolbox 로딩 구조가 전면 개편되었으며, 이전 버전은 더 이상 지원되지 않습니다.",
        "많은 기본 유틸리티 기능이 Widget Tools로 이전되어 이제 Toolbox 전용이 아니며, WidgetTools.utilities 컬렉션을 통해 전역적으로 접근할 수 있습니다.",
        "Toolbox 전용 데이터는 더 이상 프레임 테이블에 주입되지 않으며, 툴팁 또는 컨테이너 배치 데이터 등을 포함한 Toolbox 전용 테이블에 저장됩니다.",
        "블리자드 전역 OnEvent(및 사용자 정의 이벤트) 핸들러를 관리하는 이벤트 처리 백엔드 시스템이 업데이트되었으며, WidgetTools.utilities 컬렉션을 통해 전역적으로 접근 가능한 새로운 유틸리티가 추가되었습니다.",
        "사용자 지정 가능한 프레임, 버튼 및 기타 위젯은 이제 새로운 생성자를 통해 만들어야 하며, 기본 객체에서 사용자 지정 플래그가 제거되었습니다.",
        "개발 전용 주석 대부분이 설치된 애드온 파일 외부로 이동되어 설치 용량이 크게 줄었습니다.",
        "데이터 관리 설정 페이지(이제 '프로필 페이지'로 명명)의 구성 로직이 profilemanager 위젯과 그 위에 적용되는 GUI 변형으로 분리되어, 향후 개발 유연성과 사용자 지정 가능성이 향상되었습니다.",
        "기타 여러 내부 변경 및 개선이 이루어졌습니다.",
        "#F_핫픽스들:_#",
        "수많은 기타 작은 수정 사항이 포함되었습니다.",
        "#H_도움, 제안 및 버그 제보에 감사드립니다 !_# 문제가 발생하면 언제든지 제보해주세요. 문제가 언제, 어떻게 발생했는지, 그리고 (관련이 있다면) 어떤 다른 애드온을 사용 중인지 알려주시면 재현 및 수정에 큰 도움이 됩니다. 가능하다면 Lua 오류 메시지와 taint 로그도 함께 제공해주세요.",
    }
}

--[ Strings ]

--NOTE: #FLAGS will be replaced by text or number values via code; \n represents the newline character

---Korean
---@class toolboxStrings_koKR
wt.strings = {
	date = "#YEAR년 #MONTH월 #DAY일",

	override = "덮어쓰기",
	example = "예시",

	chat_welcome_thanks = "#ADDON을(를) 사용해 주셔서 감사합니다!",
	chat_welcome_hint = "#KEYWORD를 입력하여 채팅 명령어 목록을 확인하세요.",
	chat_welcome_keywords = "#KEYWORD 또는 #KEYWORD_ALTERNATE",
	chat_help_list = "#ADDON 채팅 명령어 목록:",

	popupInput_title = "텍스트를 입력하세요",
	popupInput_tooltip = KEY_ENTER .. "를 눌러 입력한 텍스트를 적용하거나 " .. KEY_ESCAPE .. "를 눌러 취소합니다.",

	reload_title = "적용 대기 중인 변경 사항",
	reload_description = "변경 사항을 적용하려면 인터페이스를 다시 불러오세요.",
	reload_accept_label = "지금 다시 불러오기",
	reload_accept_tooltip = "지금 인터페이스를 다시 불러와 변경 사항을 적용할 수 있습니다.",
	reload_cancel_label = "나중에",
	reload_cancel_tooltip = "/reload 명령어나 로그아웃으로 나중에 인터페이스를 다시 불러올 수 있습니다.",

	multiSelector_locked = "잠김",
	multiSelector_minLimit = "#MIN개 이상의 옵션을 선택해야 합니다.",
	multiSelector_maxLimit = "한 번에 #MAX개 옵션만 선택할 수 있습니다.",

	dropdown_selected = "현재 선택된 옵션입니다.",
	dropdown_none = "선택된 옵션이 없습니다.",
	dropdown_open = "옵션 목록을 보려면 클릭하세요.",
	dropdown_previous_label = "이전 옵션",
	dropdown_previous_tooltip = "이전 옵션을 선택합니다.",
	dropdown_next_label = "다음 옵션",
	dropdown_next_tooltip = "다음 옵션을 선택합니다.",
	dropdown_clear = "선택 지우기",

	copyBox_tooltip = "텍스트 복사:\n" .. CTRL_KEY_TEXT .." + C (Windows)\n" .. COMMAND .. " + C (Mac)",

	slider_value_label = "값 지정",
	slider_value_tooltip = "범위 내의 값을 입력하세요.",
	slider_decrease_label = "감소",
	slider_decrease_tooltip = {
		"값에서 #VALUE만큼 뺍니다.",
		"ALT를 누르고 있으면 대신 #VALUE만큼 뺍니다.",
	},
	slider_increase_label = "증가",
	slider_increase_tooltip = {
		"값에 #VALUE만큼 더합니다.",
		"ALT를 누르고 있으면 대신 #VALUE만큼 더합니다.",
	},

	color_picker_label = "색상 선택",
	color_picker_tooltip = "색상 선택기를 열어 #ALPHA색상을 설정하세요.",
	color_picker_alpha = "불투명도와 ",
	color_hex_label = "HEX 색상 코드로 추가",
	color_hex_tooltip = "색상 선택기 대신 HEX 코드로 색상을 변경할 수 있습니다.",

	settings_save = "닫을 때 변경 사항이 적용됩니다.",
	settings_cancel_label = "변경 사항 되돌리기",
	settings_cancel_tooltip = "이 페이지에서 변경한 내용을 모두 취소하고 저장된 값을 불러옵니다.",
	settings_defaults_label = "기본값 복원",
	settings_defaults_tooltip = "이 페이지(또는 전체 카테고리)의 모든 설정을 기본값으로 복원합니다.",
	settings_warning = "#PAGE 페이지 또는 #CATEGORY 카테고리의 모든 설정을 기본값으로 초기화하시겠습니까?",
	settings_warningSingle = "#PAGE 페이지의 설정을 기본값으로 초기화하시겠습니까?",

	value_copy = "값 복사",
	value_paste = "값 붙여넣기",
	value_revert = "변경 사항 되돌리기",
	value_restore = "기본값 복원",
	value_note = "오른쪽 클릭으로 복사하거나 되돌릴 수 있습니다.",

	points_left = "왼쪽",
	points_right = "오른쪽",
	points_center = "가운데",
	points_top_left = "왼쪽 상단",
	points_top_right = "오른쪽 상단",
	points_top_center = "가운데 상단",
	points_bottom_left = "왼쪽 하단",
	points_bottom_right = "오른쪽 하단",
	points_bottom_center = "가운데 하단",

	strata_lowest = "최하단 배경",
	strata_lower = "중간 배경",
	strata_low = "상위 배경",
	strata_lowMid = "하위 중간",
	strata_highMid = "상위 중간",
	strata_high = "하위 전경",
	strata_higher = "중간 전경",
	strata_highest = "상위 전경",

	about_title = "정보",
	about_description = "#ADDON을(를) 사용해 주셔서 감사합니다! 피드백을 보내거나 도움을 받고 개발을 지원하는 방법을 확인하려면 링크를 복사하세요.",
	about_version = "버전",
	about_date = "날짜",
	about_author = "제작자",
	about_license = "라이선스",
	about_curseForge = "CurseForge 페이지",
	about_wago = "Wago 페이지",
	about_repository = "GitHub 저장소",
	about_issues = "문제 및 피드백",
	about_changelog_label = "업데이트 노트",
	about_changelog_tooltip = "최신 버전(#VERSION)에 적용된 모든 변경, 업데이트, 수정 사항 노트입니다.",
	about_fullChangelog_label = "#ADDON 변경 기록",
	about_fullChangelog_tooltip = "모든 애드온 버전의 전체 업데이트 노트 목록입니다.",
	about_fullChangelog_open_label = "변경 기록",
	about_fullChangelog_open_tooltip = "모든 애드온 버전의 전체 업데이트 노트를 확인하세요.",

	sponsors_title = "후원자",
	sponsors_description = "지속적인 후원에 진심으로 감사드립니다!",

	profilesPage_title = "프로필 & 백업",
	profilesPage_description = "프로필 및 백업을 가져오기/내보내기로 #ADDON 설정을 추가로 관리하세요.",

	profiles_title = "프로필",
	profiles_description = "각 캐릭터별로 고유한 옵션 프로필을 생성, 편집, 적용할 수 있습니다.",
	profiles_select_label = "프로필 선택",
	profiles_select_tooltip = "현재 캐릭터에 사용할 옵션 데이터 저장 프로필을 선택하세요.\n\n활성 프로필의 데이터는 설정을 수정하고 저장할 때 자동으로 덮어씌워집니다!",
	profiles_select_profile = "프로필",
	profiles_select_main = "메인",
	profiles_new_label = "새 프로필",
	profiles_new_tooltip = "새 기본 프로필을 생성합니다.",
	profiles_duplicate_label = "복제",
	profiles_duplicate_tooltip = "현재 활성 프로필의 데이터를 복사하여 새 프로필을 만듭니다.",
	profiles_rename_label = "이름 변경",
	profiles_rename_tooltip = "현재 활성 프로필의 이름을 변경합니다.",
	profiles_rename_description = "#PROFILE의 이름을 다음으로 변경:",
	profiles_delete_tooltip = "현재 활성 프로필을 삭제합니다.",
	profiles_delete_warning = "현재 활성 #PROFILE #ADDON 설정 프로필을 삭제하고 저장된 모든 데이터를 영구적으로 삭제하시겠습니까?",
	profiles_reset_warning = "현재 활성 #PROFILE #ADDON 설정 프로필을 기본값으로 덮어쓰시겠습니까?",

	backup_title = "백업",
	backup_description = "현재 활성 프로필의 데이터를 가져오기/내보내기로 저장, 공유, 이동하거나 값을 직접 수정할 수 있습니다.",
	backup_box_label = "현재 프로필 가져오기/내보내기",
	backup_box_tooltip = {
		"이 입력란의 백업 문자열에는 현재 활성 애드온 프로필 데이터가 포함되어 있습니다.",
		"텍스트를 복사하여 데이터를 저장, 공유하거나 다른 계정에 불러올 수 있습니다.",
		"가지고 있는 문자열로 데이터를 불러오려면 이 입력란의 텍스트를 덮어쓴 후 " .. KEY_ENTER .. "를 누르거나 #LOAD 버튼을 클릭하세요.",
		"참고: 커스텀 폰트나 텍스처 파일을 사용하는 경우, 해당 파일은 이 문자열로 함께 전송되지 않습니다. 별도로 저장 후 애드온 폴더에 넣어야 사용할 수 있습니다.",
		"직접 확인했거나 신뢰하는 소스의 문자열만 불러오세요!",
	},
	backup_allProfiles_label = "모든 프로필 가져오기/내보내기",
	backup_allProfiles_tooltipLine = "이 입력란의 백업 문자열에는 모든 애드온 프로필 목록과 각 프로필에 저장된 데이터, 그리고 현재 활성 프로필 이름이 포함되어 있습니다.",
	backup_allProfiles_open_label = "모든 프로필",
	backup_allProfiles_open_tooltip = "전체 프로필 목록에 접근하여 각 프로필의 데이터를 백업하거나 수정할 수 있습니다.",
	backup_compact_label = "간단히",
	backup_compact_tooltip = "간단한 보기와 더 읽기 쉽고 편집 가능한 보기로 전환합니다.",
	backup_load_label = "불러오기",
	backup_load_tooltip = "현재 문자열을 확인하고 데이터를 불러옵니다.",
	backup_reset_tooltip = "문자열에 적용된 모든 변경 사항을 취소하고 현재 저장된 데이터로 초기화합니다.",
	backup_import = "문자열 불러오기",
	backup_warning = "현재 입력된 문자열을 불러오시겠습니까?\n\n저장되지 않은 모든 변경 사항이 취소됩니다.\n\n온라인 소스에서 복사했거나 다른 사람이 보낸 경우, 내부 코드를 확인하고 신뢰할 수 있을 때만 불러오세요.\n\n신뢰하지 않는 소스라면 원치 않는 동작을 방지하기 위해 취소하는 것이 좋습니다.",
	backup_error = "제공된 백업 문자열을 검증할 수 없어 데이터를 불러오지 못했습니다. 일부 문자가 누락되었거나 편집 중 오류가 발생했을 수 있습니다.",

	position_title = "위치",
	position_description_static = "#FRAME의 화면 내 위치를 여기서 세밀하게 조정하세요.",
	position_description_movable = "SHIFT를 누른 채 #FRAME을 드래그하여 원하는 위치로 옮기고, 여기서 세밀하게 조정하세요.",
	position_relativePoint_label = "화면 기준점",
	position_relativePoint_tooltip = "#FRAME의 선택한 연결 기준점을 여기에서 선택한 화면 기준점에 연결합니다.",
	-- position_relativeTo_label = "프레임에 연결",
	-- position_relativeTo_tooltip = "다른 UI 요소(프레임) 이름을 입력하여 #FRAME의 위치를 연결할 수 있습니다.\n\n/framestack 명령어로 프레임 이름을 확인할 수 있습니다.",
	position_anchor_label = "연결 기준점",
	position_anchor_tooltip = "선택한 화면 기준점에 연결할 때 #FRAME이 어느 지점에서 고정될지 선택하세요.",
	position_keepInPlace_label = "위치 유지",
	position_keepInPlace_tooltip = "#ANCHOR를 변경해도 #FRAME을 이동하지 않고 오프셋 값만 업데이트합니다.",
	position_offsetX_label = "수평 오프셋",
	position_offsetX_tooltip = "선택한 #ANCHOR로부터 #FRAME의 수평(X축) 오프셋을 설정합니다.",
	position_offsetY_label = "수직 오프셋",
	position_offsetY_tooltip = "선택한 #ANCHOR로부터 #FRAME의 수직(Y축) 오프셋을 설정합니다.",
	position_keepInBounds_label = "화면 내에 유지",
	position_keepInBounds_tooltip = "#FRAME이 화면 밖으로 나가지 않도록 합니다.",

	presets_apply_label = "프리셋 적용",
	presets_apply_tooltip = "#FRAME의 위치를 아래 프리셋 중 하나를 선택해 변경하세요.",
	presets_apply_list = { "미니맵 아래", },
	presets_apply_select = "프리셋 선택…",
	presets_save_label = "#CUSTOM 프리셋 업데이트",
	presets_save_tooltip = "현재 #FRAME의 위치와 표시 상태를 #CUSTOM 프리셋에 저장합니다.",
	presets_save_warning = "#CUSTOM 프리셋을 현재 값으로 덮어쓰시겠습니까?",
	presets_reset_label = "#CUSTOM 프리셋 초기화",
	presets_reset_tooltip = "저장된 #CUSTOM 프리셋 데이터를 기본값으로 덮어쓰고 적용합니다.",
	presets_reset_warning = "#CUSTOM 프리셋을 기본값으로 덮어쓰시겠습니까?",

	layer_strata_label = "화면 레이어",
	layer_strata_tooltip = "#FRAME을 다른 UI 요소보다 앞이나 뒤로 이동시킵니다.",
	layer_keepOnTop_label = "마우스 상호작용 시 위로 표시",
	layer_keepOnTop_tooltip = "마우스 상호작용 시 #FRAME이 같은 #STRATA 내 다른 프레임 위로 이동할 수 있도록 허용합니다.",
	layer_level_label = "프레임 레벨",
	layer_level_tooltip = "같은 #STRATA 스택 내에서 #FRAME이 위/아래에 위치할 정확한 레벨입니다.",

	font_title = "텍스트",
	font_path_label = "글꼴",
	font_path_tooltip = "글꼴을 선택하세요.",
	font_path_default_label = "지역화된 기본 글꼴",
	font_path_default_tooltip = "이것은 블리자드에서 사용하는 지역화된 기본 글꼴입니다.",
	font_path_base = "이것은 기본 게임 글꼴입니다.",
	font_path_custom = "이것은 사용자 지정 글꼴입니다.",
	font_path_otf = "OpenType 글꼴 라이선스.",
	font_path_file = "파일 경로: #PATH",
	font_path_replace = "사용자 지정 옵션은 #FILE_CUSTOM 글꼴 파일을\n#FONTS_DIRECTORY\n내에서 찾을 수 있는 다른 TrueType 글꼴 파일로 교체하여 완전한 사용자 지정을 제공합니다. 단, 원래의 #FILE_CUSTOM 파일 이름은 유지해야 합니다.",
	font_path_reminder = "글꼴 파일을 교체한 후 변경 사항을 적용하려면 게임 클라이언트를 완전히 재시작해야 할 수 있습니다.",
	font_size_label = "크기",
	font_size_tooltip = "글꼴 크기를 설정하세요.",
	font_alignment_label = "정렬",
	font_alignment_tooltip = "텍스트의 가로 정렬을 선택하세요.",
	font_color_label = "#COLOR_TYPE 색상",
	font_color_tooltip = "#COLOR_TYPE 텍스트 색상을 설정하세요.",
}