local wt = WidgetTools.toolboxes.initialization[C_AddOns.GetAddOnMetadata(..., "Version")] ---@type toolbox

if not wt then return end

--[ Changelog ]

wt.changelog = {
    {
        "#V_Version 3.0_# #H_(23/4/2026)_#",
        "#F_热修复（版本 3.0.1）：_#",
        "在多个位置添加了保护措施，以防止缺失或无效的资源文件路径（字体或材质）导致严重错误。",
        "#N_新增:_#",
        "新增对 Midnight 12.0.5 的支持。",
        "此前添加的设置右键菜单进一步增强，加入了复制与粘贴功能，可轻松在相似类型的设置之间移动数值。",
        "新增一个用于管理字体选项的高级设置模板（未来更新将加入更多字体自定义选项）。",
        "#C_更改:_#",
        "设置中的数字滑块外观已更新，以匹配新的暴雪滑块，同时保留所有基于 Widget Tools Toolboxes 的插件增强功能。",
        "Toolbox 的加载结构已全面重构，不再支持旧版本。",
        "许多基础工具函数已移交给 Widget Tools（不再是 Toolbox 专属），可通过 WidgetTools.utilities 全局访问。",
        "Toolbox 专属数据将不再注入到框架表中，而是存放在 Toolbox 专属表中（包括提示信息或容器内容布局数据）。",
        "用于管理暴雪全局 OnEvent（以及自定义事件）处理器的事件处理后台系统已更新，并新增可通过 WidgetTools.utilities 全局访问的工具函数。",
        "可自定义的框架、按钮和其他组件现在必须通过新的构造函数创建，其基础版本中的自定义标记已被移除.",
        "大部分仅用于开发的注释已移出插件安装文件，以大幅减少安装体积。",
        "数据管理设置页面（现称为“配置文件页面”）的构建逻辑已拆分为一个 profilemanager 组件及其上的 GUI 变体，以提供更高的开发灵活性和自定义能力。",
        "其他多项底层改进与优化。",
        "#F_热修复项:_#",
        "大量其他小型修复。",
        "#H_感谢大家的帮助、建议与错误报告 !_# 如果遇到任何问题，请务必反馈！请尽量说明问题发生的时间、方式，以及（如相关）你正在使用的其他插件，以便我能更好地复现并修复问题。如有可能，请附上 Lua 错误信息与 taint 日志。",
    }
}

--[ Strings ]

--NOTE: #FLAGS will be replaced by text or number values via code; \n represents the newline character

---Chinese (simplified, PRC)
---@class toolboxStrings_zhCN
wt.strings = {
	date = "#YEAR/#MONTH/#DAY",

	override = "覆盖",
	example = "示例",

	chat_welcome_thanks = "感谢您使用#ADDON！",
	chat_welcome_hint = "输入#KEYWORD查看聊天命令列表。",
	chat_welcome_keywords = "#KEYWORD 或 #KEYWORD_ALTERNATE",
	chat_help_list = "#ADDON 聊天命令列表：",

	popupInput_title = "请输入文本",
	popupInput_tooltip = "按" .. KEY_ENTER .. "确认输入的文本，或按" .. KEY_ESCAPE .. "取消。",

	reload_title = "待应用更改",
	reload_description = "请重新加载界面以应用待处理的更改。",
	reload_accept_label = "立即重载",
	reload_accept_tooltip = "您可以选择现在重载界面以应用更改。",
	reload_cancel_label = "稍后",
	reload_cancel_tooltip = "稍后可通过/reload命令或注销来重载界面。",

	multiSelector_locked = "已锁定",
	multiSelector_minLimit = "至少需要选择 #MIN 个选项。",
	multiSelector_maxLimit = "一次只能选择 #MAX 个选项。",

	dropdown_selected = "这是当前选中的选项。",
	dropdown_none = "尚未选择任何选项。",
	dropdown_open = "点击查看选项列表。",
	dropdown_previous_label = "上一个选项",
	dropdown_previous_tooltip = "选择上一个选项。",
	dropdown_next_label = "下一个选项",
	dropdown_next_tooltip = "选择下一个选项。",
	dropdown_clear = "清除选择",

	copyBox_tooltip = "按下：\n" .. CTRL_KEY_TEXT .. " + C (Windows)\n" .. COMMAND .. " + C (Mac) 复制文本",

	slider_value_label = "请输入数值",
	slider_value_tooltip = "输入范围内的任意数值。",
	slider_decrease_label = "减少",
	slider_decrease_tooltip = {
		"从当前值减去#VALUE。",
		"按住ALT则改为减去#VALUE。",
	},
	slider_increase_label = "增加",
	slider_increase_tooltip = {
		"将#VALUE加到当前值。",
		"按住ALT则改为加上#VALUE。",
	},

	color_picker_label = "选择颜色",
	color_picker_tooltip = "打开颜色选择器自定义颜色#ALPHA。",
	color_picker_alpha = "并调整不透明度",
	color_hex_label = "通过HEX颜色码添加",
	color_hex_tooltip = "您可以通过HEX颜色码更改颜色，而不是使用颜色选择器。",

	settings_save = "关闭时将应用更改。",
	settings_cancel_label = "撤销更改",
	settings_cancel_tooltip = "放弃本页所有更改并加载已保存的值。",
	settings_defaults_label = "恢复默认",
	settings_defaults_tooltip = "将本页（或整个分类）的所有设置恢复为默认值。",
	settings_warning = "确定要将#PAGE页面或#CATEGORY分类的所有设置恢复为默认值吗？",
	settings_warningSingle = "确定要将#PAGE页面的设置恢复为默认值吗？",

	value_copy = "复制数值",
	value_paste = "粘贴数值",
	value_revert = "撤销更改",
	value_restore = "恢复默认",
	value_note = "右键点击可复制或撤销。",

	points_left = "左",
	points_right = "右",
	points_center = "中",
	points_top_left = "左上",
	points_top_right = "右上",
	points_top_center = "上方居中",
	points_bottom_left = "左下",
	points_bottom_right = "右下",
	points_bottom_center = "下方居中",

	strata_lowest = "最低背景",
	strata_lower = "中等背景",
	strata_low = "高背景",
	strata_lowMid = "中层偏低",
	strata_highMid = "中层偏高",
	strata_high = "低前景",
	strata_higher = "中前景",
	strata_highest = "高前景",

	about_title = "关于",
	about_description = "感谢您使用#ADDON！复制下方链接以反馈、获取帮助或支持开发。",
	about_version = "版本",
	about_date = "日期",
	about_author = "作者",
	about_license = "许可证",
	about_curseForge = "CurseForge页面",
	about_wago = "Wago页面",
	about_repository = "GitHub仓库",
	about_issues = "问题与反馈",
	about_changelog_label = "更新说明",
	about_changelog_tooltip = "本次版本（#VERSION）所有更改、更新与修复说明。",
	about_fullChangelog_label = "#ADDON更新日志",
	about_fullChangelog_tooltip = "所有插件版本的完整更新说明列表。",
	about_fullChangelog_open_label = "更新日志",
	about_fullChangelog_open_tooltip = "阅读所有插件版本的完整更新说明。",

	sponsors_title = "赞助者",
	sponsors_description = "非常感谢您的持续支持！",

	profilesPage_title = "配置文件 & 备份",
	profilesPage_description = "通过导入和导出管理配置文件与备份，进一步配置#ADDON。",

	profiles_title = "配置文件",
	profiles_description = "为每个角色创建、编辑并应用专属配置文件。",
	profiles_select_label = "选择配置文件",
	profiles_select_tooltip = "选择当前角色要使用的配置文件。\n\n当设置更改并保存时，激活的配置文件数据会自动被覆盖！",
	profiles_select_profile = "配置文件",
	profiles_select_main = "主",
	profiles_new_label = "新建配置文件",
	profiles_new_tooltip = "创建一个使用默认设置的新配置文件。",
	profiles_duplicate_label = "复制",
	profiles_duplicate_tooltip = "以当前激活的配置文件数据创建新配置文件。",
	profiles_rename_label = "重命名",
	profiles_rename_tooltip = "重命名当前激活的配置文件。",
	profiles_rename_description = "将#PROFILE重命名为：",
	profiles_delete_tooltip = "删除当前激活的配置文件。",
	profiles_delete_warning = "确定要移除当前激活的#PROFILE #ADDON配置文件并永久删除其中所有数据吗？",
	profiles_reset_warning = "确定要将当前激活的#PROFILE #ADDON配置文件覆盖为默认值吗？",

	backup_title = "备份",
	backup_description = "导入或导出当前激活配置文件的数据以保存、分享、迁移设置，或手动编辑特定值。",
	backup_box_label = "导入或导出当前配置文件",
	backup_box_tooltip = {
		"此文本框中的备份字符串包含当前激活的插件配置文件数据。",
		"复制文本以保存、分享或为其他账号加载数据。",
		"如需从字符串加载数据，请覆盖此文本框内的文本后按" .. KEY_ENTER .. "或点击#LOAD按钮。",
		"注意：如果您使用自定义字体或材质文件，这些文件不会随字符串一起转移。需单独保存并放入插件文件夹。",
		"请仅加载您亲自验证过或来自可信来源的字符串！",
	},
	backup_allProfiles_label = "导入或导出所有配置文件",
	backup_allProfiles_tooltipLine = "此文本框中的备份字符串包含所有插件配置文件及其数据，以及当前激活配置文件的名称。",
	backup_allProfiles_open_label = "所有配置文件",
	backup_allProfiles_open_tooltip = "访问完整配置文件列表并备份或修改各自数据。",
	backup_compact_label = "精简",
	backup_compact_tooltip = "在精简和更易读/可编辑视图间切换。",
	backup_load_label = "加载",
	backup_load_tooltip = "检查当前字符串并尝试加载数据。",
	backup_reset_tooltip = "放弃对字符串的所有更改，并重置为当前保存的数据。",
	backup_import = "加载字符串",
	backup_warning = "确定要尝试加载当前输入的字符串吗？\n\n所有未保存的更改将被放弃。\n\n如果您是从网络来源复制或他人发送，仅在确认内容安全时加载。\n\n如不信任来源，建议取消以避免意外操作。",
	backup_error = "无法验证提供的备份字符串，未加载任何数据。可能缺少字符或编辑时出现错误。",

	position_title = "位置",
	position_description_static = "可在此微调#FRAME在屏幕上的位置。",
	position_description_movable = "按住SHIFT拖动#FRAME到屏幕任意位置，并可在此微调。",
	position_relativePoint_label = "屏幕连接点",
	position_relativePoint_tooltip = "将#FRAME选定的锚点连接到此处选择的屏幕连接点。",
	-- position_relativeTo_label = "连接到框体",
	-- position_relativeTo_tooltip = "输入其他UI元素名称，将#FRAME位置连接到该框体。\n\n可用/framestack命令查询框体名称。",
	position_anchor_label = "连接锚点",
	position_anchor_tooltip = "选择#FRAME连接到屏幕连接点时要从哪个锚点对齐。",
	position_keepInPlace_label = "保持原位",
	position_keepInPlace_tooltip = "更改#ANCHOR时不移动#FRAME，只更新偏移值。",
	position_offsetX_label = "水平偏移",
	position_offsetX_tooltip = "设置#FRAME相对于选定#ANCHOR的水平（X轴）偏移量。",
	position_offsetY_label = "垂直偏移",
	position_offsetY_tooltip = "设置#FRAME相对于选定#ANCHOR的垂直（Y轴）偏移量。",
	position_keepInBounds_label = "保持在屏幕内",
	position_keepInBounds_tooltip = "确保#FRAME不会被移出屏幕范围。",

	presets_apply_label = "应用预设",
	presets_apply_tooltip = "选择并应用下列预设以更改#FRAME位置。",
	presets_apply_list = { "小地图下方", },
	presets_apply_select = "选择预设…",
	presets_save_label = "更新#CUSTOM预设",
	presets_save_tooltip = "将当前#FRAME的位置和可见性保存到#CUSTOM预设。",
	presets_save_warning = "确定要用当前值覆盖#CUSTOM预设吗？",
	presets_reset_label = "重置#CUSTOM预设",
	presets_reset_tooltip = "用默认值覆盖#CUSTOM预设数据并应用。",
	presets_reset_warning = "确定要用默认值覆盖#CUSTOM预设吗？",

	layer_strata_label = "屏幕层级",
	layer_strata_tooltip = "提高或降低#FRAME的层级，使其显示在其他UI元素的前方或后方。",
	layer_keepOnTop_label = "鼠标交互时置顶",
	layer_keepOnTop_tooltip = "与#FRAME交互时，允许将其提升到同一#STRATA内其他框体的上方。",
	layer_level_label = "框体层级",
	layer_level_tooltip = "#FRAME在同一#STRATA堆栈中上下的精确位置。",

	font_title = "文本",
	font_path_label = "字体",
	font_path_tooltip = "选择字体。",
	font_path_default_label = "本地化默认字体",
	font_path_default_tooltip = "这是 Blizzard 使用的本地化默认字体。",
	font_path_base = "这是基础游戏字体。",
	font_path_custom = "这是自定义字体。",
	font_path_otf = "OpenType 字体许可。",
	font_path_file = "文件路径：#PATH",
	font_path_replace = "自定义选项提供完全自定义功能，允许您将 #FILE_CUSTOM 字体文件替换为在\n#FONTS_DIRECTORY\n中找到的任何 TrueType 字体文件，同时保持原有的 #FILE_CUSTOM 文件名。",
	font_path_reminder = "替换字体文件后，您可能需要完全重启游戏客户端才能应用更改。",
	font_size_label = "大小",
	font_size_tooltip = "设置字体大小。",
	font_alignment_label = "对齐",
	font_alignment_tooltip = "选择文本的水平对齐方式。",
	font_color_label = "#COLOR_TYPE 颜色",
	font_color_tooltip = "设置 #COLOR_TYPE 文本颜色。",
}