local wt = WidgetTools.toolboxes.initialization[C_AddOns.GetAddOnMetadata(..., "Version")] ---@type toolbox

if not wt then return end

--[ Changelog ]

wt.changelog = {
    {
        "#V_Version 3.0_# #H_(23/4/2026)_#",
        "#F_熱修復（版本 3.0.1）：_#",
        "在多個位置加入了保護機制，以避免遺失或無效的資源檔案路徑（字體或材質）導致嚴重錯誤。",
        "#N_新增:_#",
        "新增對 Midnight 12.0.5 的支援。",
        "先前加入的設定右鍵選單進一步強化，新增複製與貼上功能，可輕鬆在相似類型的設定之間移動數值。",
        "新增一個用於管理字體選項的進階設定範本（未來更新將加入更多字體自訂功能）。",
        "#C_變更:_#",
        "設定中的數字滑桿外觀已更新，以符合新的暴雪滑桿，同時保留所有基於 Widget Tools Toolboxes 的插件強化功能。",
        "Toolbox 的載入結構已全面重製，不再支援舊版本。",
        "許多基本工具函式已移交給 Widget Tools（不再是 Toolbox 專屬），可透過 WidgetTools.utilities 全域存取。",
        "Toolbox 專屬資料將不再注入至框架表，而是存放於 Toolbox 專屬表中（包含提示訊息或容器內容排列資料）。",
        "管理暴雪全域 OnEvent（以及自訂事件）處理器的事件後端系統已更新，並新增可透過 WidgetTools.utilities 全域存取的工具函式。",
        "可自訂的框架、按鈕與其他元件現在必須透過新的建構子建立，其基礎版本中的自訂旗標已被移除。",
        "大部分僅供開發使用的註解已移出插件安裝檔案，以大幅減少安裝大小。",
        "資料管理設定頁面（現稱為「設定檔頁面」）的建構邏輯已拆分為 profilemanager 元件與其上的 GUI 變體，以提供更高的開發彈性與自訂能力。",
        "其他多項底層改善與優化。",
        "#F_熱修復項:_#",
        "許多其他小型修正。",
        "#H_感謝大家的協助、建議與錯誤回報 !_# 若遇到任何問題，請務必回報！請盡量說明問題發生的時間、方式，以及（若相關）你正在使用的其他插件，以便我能更容易重現並修正問題。如有可能，請附上 Lua 錯誤訊息與 taint 記錄。",
    }
}

--[ Strings ]

--NOTE: #FLAGS will be replaced by text or number values via code; \n represents the newline character

---Chinese (traditional, Taiwan)
---@class toolboxStrings_zhTW
wt.strings = {
	date = "#YEAR/#MONTH/#DAY",

	override = "覆蓋",
	example = "範例",

	chat_welcome_thanks = "感謝您使用#ADDON！",
	chat_welcome_hint = "輸入#KEYWORD來查看聊天指令列表。",
	chat_welcome_keywords = "#KEYWORD 或 #KEYWORD_ALTERNATE",
	chat_help_list = "#ADDON 聊天指令列表：",

	popupInput_title = "請輸入文字",
	popupInput_tooltip = "按下" .. KEY_ENTER .. "以接受輸入的文字，或按" .. KEY_ESCAPE .. "以取消。",

	reload_title = "有待套用的變更",
	reload_description = "請重新載入介面以套用變更。",
	reload_accept_label = "立即重載",
	reload_accept_tooltip = "您可以選擇現在重載介面以套用變更。",
	reload_cancel_label = "稍後",
	reload_cancel_tooltip = "稍後可使用 /reload 指令或登出來重載介面。",

	multiSelector_locked = "已鎖定",
	multiSelector_minLimit = "至少需選擇 #MIN 個選項。",
	multiSelector_maxLimit = "一次只能選擇 #MAX 個選項。",

	dropdown_selected = "這是目前選擇的選項。",
	dropdown_none = "尚未選擇任何選項。",
	dropdown_open = "點擊以檢視選項列表。",
	dropdown_previous_label = "上一個選項",
	dropdown_previous_tooltip = "選擇上一個選項。",
	dropdown_next_label = "下一個選項",
	dropdown_next_tooltip = "選擇下一個選項。",
	dropdown_clear = "清除選取",

	copyBox_tooltip = "請按下：\n" .. CTRL_KEY_TEXT .." + C (Windows)\n" .. COMMAND .. " + C (Mac) 來複製文字",

	slider_value_label = "請輸入數值",
	slider_value_tooltip = "請輸入範圍內的數值。",
	slider_decrease_label = "減少",
	slider_decrease_tooltip = {
		"從數值中減去 #VALUE。",
		"按住 ALT 則改為減去 #VALUE。",
	},
	slider_increase_label = "增加",
	slider_increase_tooltip = {
		"將 #VALUE 加到數值中。",
		"按住 ALT 則改為加上 #VALUE。",
	},

	color_picker_label = "選擇顏色",
	color_picker_tooltip = "開啟顏色選擇器自訂顏色#ALPHA。",
	color_picker_alpha = "並調整不透明度",
	color_hex_label = "以 HEX 色碼新增",
	color_hex_tooltip = "您也可以直接輸入 HEX 色碼來變更顏色。",

	settings_save = "關閉時將套用變更。",
	settings_cancel_label = "還原變更",
	settings_cancel_tooltip = "放棄本頁所有變更並載入已儲存的值。",
	settings_defaults_label = "恢復預設值",
	settings_defaults_tooltip = "將本頁（或整個分類）所有設定恢復為預設值。",
	settings_warning = "確定要將 #PAGE 頁面或 #CATEGORY 分類的所有設定恢復為預設值嗎？",
	settings_warningSingle = "確定要將 #PAGE 頁面的設定恢復為預設值嗎？",

	value_copy = "複製數值",
	value_paste = "貼上數值",
	value_revert = "還原變更",
	value_restore = "恢復預設",
	value_note = "右鍵點擊可複製或還原。",

	points_left = "左",
	points_right = "右",
	points_center = "中",
	points_top_left = "左上",
	points_top_right = "右上",
	points_top_center = "上方中央",
	points_bottom_left = "左下",
	points_bottom_right = "右下",
	points_bottom_center = "下方中央",

	strata_lowest = "最低背景",
	strata_lower = "中等背景",
	strata_low = "高背景",
	strata_lowMid = "中層偏低",
	strata_highMid = "中層偏高",
	strata_high = "低前景",
	strata_higher = "中前景",
	strata_highest = "高前景",

	about_title = "關於",
	about_description = "感謝您使用#ADDON！複製下方連結以提供回饋、取得協助或支持開發。",
	about_version = "版本",
	about_date = "日期",
	about_author = "作者",
	about_license = "授權",
	about_curseForge = "CurseForge 頁面",
	about_wago = "Wago 頁面",
	about_repository = "GitHub 儲存庫",
	about_issues = "問題與回饋",
	about_changelog_label = "更新紀錄",
	about_changelog_tooltip = "此版本（#VERSION）所有變更、更新與修正說明。",
	about_fullChangelog_label = "#ADDON 更新紀錄",
	about_fullChangelog_tooltip = "所有版本的完整更新說明列表。",
	about_fullChangelog_open_label = "更新紀錄",
	about_fullChangelog_open_tooltip = "閱讀所有版本的完整更新說明。",

	sponsors_title = "贊助者",
	sponsors_description = "感謝您的持續支持！",

	profilesPage_title = "設定檔 & 備份",
	profilesPage_description = "透過匯入與匯出管理設定檔與備份，進一步設定#ADDON。",

	profiles_title = "設定檔",
	profiles_description = "為每個角色建立、編輯並套用專屬設定檔。",
	profiles_select_label = "選擇設定檔",
	profiles_select_tooltip = "選擇目前角色要使用的設定檔。\n\n當設定變更並儲存時，啟用的設定檔資料會自動被覆蓋！",
	profiles_select_profile = "設定檔",
	profiles_select_main = "主要",
	profiles_new_label = "新增設定檔",
	profiles_new_tooltip = "建立使用預設設定的新設定檔。",
	profiles_duplicate_label = "複製",
	profiles_duplicate_tooltip = "以目前啟用的設定檔資料建立新設定檔。",
	profiles_rename_label = "重新命名",
	profiles_rename_tooltip = "重新命名目前啟用的設定檔。",
	profiles_rename_description = "將 #PROFILE 重新命名為：",
	profiles_delete_tooltip = "刪除目前啟用的設定檔。",
	profiles_delete_warning = "確定要移除目前啟用的 #PROFILE #ADDON 設定檔並永久刪除所有儲存資料嗎？",
	profiles_reset_warning = "確定要將目前啟用的 #PROFILE #ADDON 設定檔覆蓋為預設值嗎？",

	backup_title = "備份",
	backup_description = "匯入或匯出目前啟用設定檔的資料以儲存、分享、搬移設定，或手動編輯特定值。",
	backup_box_label = "匯入或匯出目前設定檔",
	backup_box_tooltip = {
		"此欄位的備份字串包含目前啟用的設定檔資料。",
		"複製文字以儲存、分享或載入到其他帳號。",
		"若要從字串載入資料，請覆蓋此欄位內容後按" .. KEY_ENTER .. "或點擊#LOAD按鈕。",
		"注意：若您使用自訂字型或材質檔案，這些檔案不會隨字串一同轉移。需另外儲存並放入插件資料夾。",
		"請僅載入您自行驗證過或來自可信來源的字串！",
	},
	backup_allProfiles_label = "匯入或匯出所有設定檔",
	backup_allProfiles_tooltipLine = "此欄位的備份字串包含所有設定檔及其資料，以及目前啟用的設定檔名稱。",
	backup_allProfiles_open_label = "所有設定檔",
	backup_allProfiles_open_tooltip = "存取完整設定檔列表並備份或修改各自資料。",
	backup_compact_label = "精簡",
	backup_compact_tooltip = "切換精簡或可讀/可編輯檢視。",
	backup_load_label = "載入",
	backup_load_tooltip = "檢查目前字串並嘗試載入資料。",
	backup_reset_tooltip = "放棄對字串的所有變更，並重設為目前儲存的資料。",
	backup_import = "載入字串",
	backup_warning = "確定要嘗試載入目前輸入的字串嗎？\n\n所有未儲存的變更將被放棄。\n\n若您是從網路來源複製或他人傳送，請確認內容安全再載入。\n\n若不信任來源，建議取消以避免不預期的行為。",
	backup_error = "無法驗證提供的備份字串，未載入任何資料。可能缺少字元或編輯時產生錯誤。",

	position_title = "位置",
	position_description_static = "可在此微調#FRAME於螢幕上的位置。",
	position_description_movable = "按住 SHIFT 拖曳#FRAME至螢幕任意位置，並可於此微調。",
	position_relativePoint_label = "螢幕連結點",
	position_relativePoint_tooltip = "將#FRAME選定的錨點連結到此處選擇的螢幕連結點。",
	-- position_relativeTo_label = "連結到框架",
	-- position_relativeTo_tooltip = "輸入其他 UI 元素名稱，將#FRAME位置連結至該框架。\n\n可用 /framestack 指令查詢框架名稱。",
	position_anchor_label = "連結錨點",
	position_anchor_tooltip = "選擇#FRAME連結到螢幕連結點時要從哪個錨點對齊。",
	position_keepInPlace_label = "保持原位",
	position_keepInPlace_tooltip = "變更#ANCHOR時不移動#FRAME，只更新偏移值。",
	position_offsetX_label = "水平偏移",
	position_offsetX_tooltip = "設定#FRAME自選定#ANCHOR的水平（X軸）偏移量。",
	position_offsetY_label = "垂直偏移",
	position_offsetY_tooltip = "設定#FRAME自選定#ANCHOR的垂直（Y軸）偏移量。",
	position_keepInBounds_label = "保持在螢幕內",
	position_keepInBounds_tooltip = "確保#FRAME不會被移出螢幕範圍。",

	presets_apply_label = "套用預設位置",
	presets_apply_tooltip = "選擇並套用下列預設位置以變更#FRAME位置。",
	presets_apply_list = { "小地圖下方", },
	presets_apply_select = "選擇預設位置…",
	presets_save_label = "更新#CUSTOM預設",
	presets_save_tooltip = "將目前#FRAME的位置與顯示狀態儲存至#CUSTOM預設。",
	presets_save_warning = "確定要以目前值覆蓋#CUSTOM預設嗎？",
	presets_reset_label = "重設#CUSTOM預設",
	presets_reset_tooltip = "以預設值覆蓋#CUSTOM預設資料並套用。",
	presets_reset_warning = "確定要以預設值覆蓋#CUSTOM預設嗎？",

	layer_strata_label = "畫面層級",
	layer_strata_tooltip = "提高或降低#FRAME的層級，使其顯示在其他 UI 元素的前方或後方。",
	layer_keepOnTop_label = "滑鼠互動時移至上層",
	layer_keepOnTop_tooltip = "與#FRAME互動時，允許將其移至同一#STRATA內其他框架之上。",
	layer_level_label = "框架層級",
	layer_level_tooltip = "#FRAME在同一#STRATA堆疊中上下的精確位置。",

	font_title = "文字",
	font_path_label = "字體",
	font_path_tooltip = "選擇字體。",
	font_path_default_label = "在地化預設字體",
	font_path_default_tooltip = "這是 Blizzard 使用的在地化預設字體。",
	font_path_base = "這是遊戲本體的字體。",
	font_path_custom = "這是自訂字體。",
	font_path_otf = "OpenType 字體授權。",
	font_path_file = "檔案路徑：#PATH",
	font_path_replace = "自訂選項提供完整的自訂功能，讓您可以將 #FILE_CUSTOM 字體檔替換為在\n#FONTS_DIRECTORY\n中找到的任何 TrueType 字體檔，同時保持原本的 #FILE_CUSTOM 檔名。",
	font_path_reminder = "替換字體檔後，您可能需要完全重新啟動遊戲客戶端才能套用變更。",
	font_size_label = "大小",
	font_size_tooltip = "設定字體大小。",
	font_alignment_label = "對齊",
	font_alignment_tooltip = "選擇文字的水平對齊方式。",
	font_color_label = "#COLOR_TYPE 顏色",
	font_color_tooltip = "設定 #COLOR_TYPE 文字顏色。",
}