--| Namespace

---@class addonNamespace
local ns = select(2, ...)

--| Shared resources

---@class widgetToolsResources
ns.rs = {}

ns.rs.addon = ...
ns.rs.title = select(2, C_AddOns.GetAddOnInfo(ns.rs.addon)):gsub("^%s*(.-)%s*$", "%1")
ns.rs.root = "Interface/AddOns/" .. ns.rs.addon .. "/"


--[[ STRINGS ]]

ns.changelog = {
	{
		"#V_Version 3.0_# #H_(23/4/2026)_#",
		"#F_Hotfix (Version 3.0.1):_#",
		"#H_The custom font file support has been reverted to the previous solution (but now handled by Widget Tools) until the next update because an oversight caused critical errors._# I have also removed several fonts to save on disk space. Once the planned custom font support is finished and released, any number of fully custom fonts will be usable to there will be little need to keep so many fonts bundled in. #H_To add a custom font file with this temporary solution, similarly like before, replace_# #O_Interface/Addons/WidgetTools/Fonts/CUSTOM.ttf_# #H_with any TrueTypeFont file, while keeping this exact file name._#",
		"Several fonts have been removed and will no not be bundled in because I would rather prioritize smaller file sizes, and having large font files that offer little benefit for most is in opposition to that goal.",
		"Added Wago ID information to help Wago to find and download addon dependencies automatically.",
		"#N_New:_#",
		"Added Midnight 12.0.5 support.",
		"A shared list of custom fonts have been added that all addons can now access via the global #H_WidgetTools.resources_# collection. #H_One custom font file named_# #O_CUSTOM.ttf_# #H_can now be placed in the main_# #O_Fonts_# #H_folder right inside the WoW client folder._# to be recognized by Widget Tools. Custom font file management is planned to be extended on in future updates.",
		"Introduced new debug logging tools accessible via the global #H_WidgetTools.debugging_# collection. Debugging features are to be expanded on and to be incorporated into Toolboxes in future updates.",
		"#C_Changes:_#",
		"The Toolbox loading structure has been overhauled, older versions are no longer supported.",
		"Many basic utility functions have been handed over to Widget Tools (and are no longer Toolbox-specific), accessible in code globally via the #H_WidgetTools.utilities_# collection.",
		"Updated the event handling backend system managing Blizzard global OnEvent (and custom event) handlers for Frames with new utilities accessible globally via the #H_WidgetTools.utilities_# collection.",
		"Most annotations that offer development-only benefits have been moved outside of installed addon files to greatly reduce install size.",
		"Several other under the hood changes & improvements.",
		"#F_Fixes:_#",
		"The AddOns menu context menu for Widget Tools will no longer take over the clickable screen space after being opened once.",
		"Numerous other smaller fixes.",
		"#O_Note:_# See Widget Toolbox  changelog on the Toolboxes & Addons page for further under the hood changes.",
		"#H_Thank you all for the help, suggestions & bug reports!_# If you encounter any issues, do not hesitate to report them! Try including when & how they occur, and which other addons are you using (when relevant) to give me the best chance of being able to reproduce & fix them. Try proving any Lua script error messages and taint logs (if you know how).",
	},
	{
		"#V_Version 2.2_# #H_(23/2/2026)_#",
		"#F_Hotfix:_#",
		"Text in editboxes will once again be properly sized to fit the width of the boxes.",
	},
	{
		"#V_Version 2.2_# #H_(13/2/2026)_#",
		"#F_Hotfix:_#",
		"Text in editboxes will once again be properly sized to fit the width of the boxes.",
	},
	{
		"#V_Version 2.1_# #H_(13/2/2026)_#",
		"#N_Updates:_#",
		"Added Midnight 12.0.1, Mists of Pandaria 5.5.3, The Burning Crusade 2.5.5 & Classic 1.15.8 support.",
		"Under the hood improvements.",
	},
	{
		"#V_Version 2.0_# #H_(8/6/2025)_#",
		"#N_New:_#",
		"Added Mists of Pandaria Classic 5.5.0, The War Within 11.2 support & Classic 1.15.7.",
		"Added AI-translated localizations for every language supported by WoW. #H_Note: Since these translations were generated by AI, they contain errors. If you'd like to help me fix some of them, or you'd like to volunteer to offer your aid to translate this addon to your language properly, do get in touch! Any help and error reports are greatly appreciated! <3_# (The Changelog will only be available in English for now.)",
		"#H_A new Lite mode has been introduced!_# When enabled, no settings pages managed by Widget Tools will be loaded for addons built with Widget Tools saving some resources in the process. Disable to access visible addon settings again. (Addon data is still loaded in the background causing no disruptions for addon functionality.)",
		"#H_Added visual aids for positioning!_# An option to enable positioning visual aids for addons built with Widget Tools has been introduced to help with understanding how the advanced positioning settings work to allow you to be in control of the finest detail.",
		"Added an option for developers to make the Frame Attributes window (TableAttributeDisplay Frame) wider.",
		"Added chat commands for Widget Tools, use: #H_/wt_# to access.",
		"#H_#C_Changes_# & #F_Fixes_#:_#",
		"The look of checkboxes & settings pages have been updated to match the new settings style.",
		"Significant under the hood improvements & fixes and other smaller changes & fixes.",
		"#V_Version 2.0.1_# • #F_Hotfix:_#",
		"Welcome messages will no longer be spammed each time the interface loads.",
		"Lite mode can now be enabled without errors.",
		"Adjusted the appearance of the Reload notice window.",
	},
	{
		"#V_Version 1.12_# #H_(8/9/2023)_#",
		"#C_Changes:_#",
		"Shortcuts have been removed from the main addon settings page in Classic.",
		"Under the hood improvements.",
	},
	{
		"#V_Version 1.11_# #H_(7/18/2023)_#",
		"#C_Changes:_#",
		"Added 1.14.4 (Classic) support with 1.14.3 backwards compatibility (until the Hardcore patch goes live).",
		"Scrolling has been improved in WotLK Classic.",
		"Backwards compatibility ensuring editboxes work with Toolbox version 1.5 has been removed.",
		"Other small improvements.",
	},
	{
		"#V_Version 1.10_# #H_(6/15/2023)_#",
		"#N_Updates:_#",
		"Added 10.1.5 (Dragonflight) support.",
		"#F_Fixes:_#",
		"No tooltip will stay on the screen after its target was hidden.",
		"Under the hood fixes & improvements.",
	},
	{
		"#V_Version 1.9_# #H_(5/17/2023)_#",
		"#C_Changes:_#",
		"Upgraded to the new Dragonflight addon logo handling. (Custom addon logos may not appear in the Interface Options in Classic clients.)",
		"#F_Fixes:_#",
		"Fixed an issue with actions being blocked after closing the Settings panel in certain situation (like changing Keybindings) in Dragonflight.",
		"The current version will now run in the WotLK Classic 3.4.2 PTR but it's not yet fully polished (as parts of the UI are still being modernized).",
		"Other small under the hood improvements & code cleanup.",
	},
	{
		"#V_Version 1.8_# #H_(4/5/2023)_#",
		"#N_Updates:_#",
		"Added 10.1 (Dragonflight) support.",
		"#F_Fixes:_#",
		"The old scrollbars have been replaced with the new scrollbars in Dragonflight, fixing any bugs that emerged with 10.1 as a result of deprecation.",
		"Several other under the hood fixes & improvements.",
	},
	{
		"#V_Version 1.7_# #H_(3/11/2023)_#",
		"#N_Updates:_#",
		"Added an option to disable addons using Widget Toolboxes from the Widget Tools settings.",
		"Added 10.0.7 (Dragonflight) support.",
		"#C_Changes:_#",
		"The Shortcuts section form the main settings page has been removed in Dragonflight (since the new expansion broke the feature - I may readd it if it gets resolved).",
		"Other smaller changes.",
		"#F_Fixes:_#",
		"Several under the hood fixes & improvements.",
	},
	{
		"#V_Version 1.6_# #H_(2/7/2023)_#",
		"#N_Updates:_#",
		"A new Sponsors section has been added to the main Settings page.\n#H_Thank you for your support! It helps me continue to spend time on developing and maintaining these addons. If you are considering supporting development as well, follow the links to see what ways are currently available._#",
		"The About info has been rearranged and combined with the Support links.",
		"Only the most recent update notes will be loaded now. The full Changelog is available in a bigger window when clicking on a new button.",
		"Made checkboxes more easily clickable, their tooltips are now visible even when the input is disabled.",
		"Added 10.0.5 (Dragonflight) & 3.4.1 (WotLK Classic) support.",
		"Numerous less notable changes & improvements.",
		"#F_Fixes:_#",
		"Widget Tools will no longer copies of its Settings after each loading screen.",
		"Settings should now be properly saved in Dragonflight, the custom Restore Defaults and Revert Changes functionalities should also work as expected now, on a per Settings page basis (with the option of restoring defaults for the whole addon kept).",
		"All other open custom Context Submenus on the same level should now close when one is opened (more Context Menu improvements are planned for a later release).",
		"Many other under the hood fixes.",
	},
	{
		"#V_Version 1.5_# #H_(11/28/2020)_#",
		"#H_Widget Tools has been supporting other addons in the background for over a year. Now, it has been separated into its own addon for more visibility, transparency and to offer wider development options._#",
		"#N_Update:_#",
		"Added Dragonflight (Retail 10.0) support with backwards compatibility.",
	}
}

ns.rs.chat = {
	keyword = "wt",
	commands = {
		about = "about",
		lite = "lite",
		debug = "debug",
	}
}


--[[ ASSETS ]]

ns.rs.colors = {
	grey = {
		{ r = 0.7, g = 0.7, b = 0.7 },
		{ r = 0.54, g = 0.54, b = 0.54 },
	},
	gold = {
		{ r = 1, g = 0.76, b = 0.07 },
		{ r = 0.8, g = 0.62, b = 0.1 },
	},
	halfTransparent = {
		grey = { r = 0.7, g = 0.7, b = 0.7, a = 0.5 },
		blue = { r = 0.7, g = 0.9, b = 1, a = 0.5 },
		yellow = { r = 1, g = 0.9, b = 0.7, a = 0.5 },
	},
	-- normal = NORMAL_FONT_COLOR,
	-- highlight = HIGHLIGHT_FONT_COLOR,
	-- disabled = GRAY_FONT_COLOR,
	-- warning = RED_FONT_COLOR,
}

ns.rs.textures = {
	logo = ns.rs.root .. "Textures/Logo.tga",
	missing = ns.rs.root .. "Textures/MissingLogo.tga",
	alphaBG = ns.rs.root .. "Textures/AlphaBG.tga",
	gradientBG = ns.rs.root .. "Textures/GradientBG.tga",
}

ns.rs.fonts = {
	{
		name = "Arbutus Slab",
		path = ns.rs.root .. "Fonts/ArbutusSlab.ttf",
	},
	{
		name = "Arial Narrow",
		path = "Fonts/ARIALN.ttf",
	},
	{
		name = "Bonbon",
		path = ns.rs.root .. "Fonts/Bonbon.ttf",
	},
	{
		name = "Caesar Dressing",
		path = ns.rs.root .. "Fonts/CaesarDressing.ttf",
	},
	{
		name = "Domine",
		path = ns.rs.root .. "Fonts/Domine.ttf",
	},
	{
		name = "Friz Quadrata",
		path = "Fonts/FRIZQT__.TTF",
	},
	{
		name = "Germania One",
		path = ns.rs.root .. "Fonts/GermaniaOne.ttf",
	},
	{
		name = "Molle",
		path = ns.rs.root .. "Fonts/Molle.ttf",
	},
	{
		name = "Morpheus",
		path = "Fonts/MORPHEUS.ttf",
	},
	{
		name = "Oregano",
		path = ns.rs.root .. "Fonts/Oregano.ttf",
	},
	{
		name = "Oxanium",
		path = ns.rs.root .. "Fonts/Oxanium.ttf",
	},
	{
		name = "Reem Kufi",
		path = ns.rs.root .. "Fonts/ReemKufi.ttf",
	},
	{
		name = "Righteous",
		path = ns.rs.root .. "Fonts/Righteous.ttf",
	},
	{
		name = "Sancreek",
		path = ns.rs.root .. "Fonts/Sancreek.ttf",
	},
	{
		name = "Skurri",
		path = "Fonts/skurri.ttf",
	},
	{
		name = "Underdog",
		path =  ns.rs.root .. "Fonts/Underdog.ttf",
	},
	{
		name = "Zen Dots",
		path =  ns.rs.root .. "Fonts/ZenDots.ttf",
	},
	{
		name = "CUSTOM", --REMOVE temporarily reinstated CUSTOM font solution once full custom font file support has been added
		path =  ns.rs.root .. "Fonts/CUSTOM.ttf",
	},
}


--[[ CLASSIC SUPPORT ]]

if not C_ColorUtil then C_ColorUtil = {
	WrapTextInColorCode = WrapTextInColorCode,
	WrapTextInColor = function(text, color)
		if type(color) ~= "table" then return text end

		if type(color["GenerateHexColor"]) ~= "function" then color = CreateColor(color.r, color.g, color.b, color.a) end

		return WrapTextInColor(text, color)
	end,
} end